[options]

; base de datos
db_host = db
db_port = 5432


; ODOO
data_dir = /var/lib/odoo

; para los modulos personalizados
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; LOGGING
log_level = info